### PR TITLE
Create .github/workflows/main.yml

### PR DESCRIPTION
**Pull request by Tyemg**
Tyemg:Tyemg-patch-1

### CODE REVIEW

**Comment by Tyemg** [comment]
Create .github/workflows/main.yml

**Comment by Tyemg** [comment]
Tyemg:Tyemg-patch-1

**Comment by Tyemg** [comment]
.github/workflows/main.yml

**Comment by GuyPaddock** [comment]
Not sure what you're proposing here but I don't think this is necessary.

**Pull request closed without merging**
